name: codebook

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
    paths-ignore:
     - 'README.md'
     - 'codebook.pdf'
  pull_request:
    branches: [ main ]
    paths-ignore:
     - 'README.md'
     - 'codebook.pdf'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check Out Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install LaTeX + fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-xetex texlive-latex-extra texlive-fonts-extra \
                                  fonts-noto-cjk fonts-inconsolata latexmk
      - name: Build PDF
        run: |
          latexmk -xelatex -shell-escape -interaction=nonstopmode -file-line-error codebook.tex

      - name: Move codebook.pdf
        run: |
          mkdir tmp
          mv codebook.pdf tmp
          git checkout pdf
          mv tmp/codebook.pdf .

      - name: Push codebook
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Optional but recommended
          # Defaults to "Apply automatic changes"
          branch: pdf
          commit_message: auto build codebook.pdf
          file_pattern: codebook.pdf